services:
  api:
    image: ${YOLO_IMAGE}
    pull_policy: always
    ports:
      - "${YOLO_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/predictions
      - AWS_REGION=${AWS_REGION}
      - AWS_DEFAULT_REGION=${AWS_REGION}     # boto3 also uses this
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}

    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    pull_policy: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-predictions}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  ollama-ui:
    image: ${OLLAMA_UI_IMAGE}
    pull_policy: always
    ports:
      - "${OLLAMA_UI_PORT:-3000}:3000"
    environment:
      YOLO_SERVICE: api:8080
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
