name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        
        script: |
          cd /home/ubuntu

          if [ ! -d "YoloServiceHadi" ]; then
            git clone https://github.com/Hadi-Serhan/YoloServiceHadi.git
          fi

          cd YoloServiceHadi

          if [ -d ".git" ]; then
            git fetch origin
            git reset --hard origin/main
          fi

          if [ ! -d ".venv" ]; then
            echo "Creating virtual environment..."
            python3 -m venv .venv
          fi

          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r torch-requirements.txt
          pip install -r requirements.txt

          sudo apt-get update
          sudo apt-get install -y ffmpeg libsm6 libxext6

          echo "Restarting the service..."
          sudo systemctl restart yolo.service

          if systemctl is-active --quiet yolo.service; then
            echo "Service restarted successfully."
          else
            echo "Service failed to start."
            exit 1
          fi

