name: Deploy Service

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        
        script: |
          cd /home/ubuntu

          # If the repo folder doesn't exist, clone it
          if [ ! -d "YoloServiceHadi" ]; then
            echo "Cloning repository..."
            git clone https://github.com/Hadi-Serhan/YoloServiceHadi.git
          fi

          cd YoloServiceHadi

          # Check if it's a git repo
          if [ -d ".git" ]; then
            echo "Fetching and resetting to origin/main..."
            git fetch origin
            git reset --hard origin/main
          else
            echo "Directory exists but is not a Git repository. Cleaning up..."
            cd ..
            rm -rf YoloServiceHadi
            git clone https://github.com/Hadi-Serhan/YoloServiceHadi.git
            cd YoloServiceHadi
          fi

          echo "Setting up environment..."
          if [ ! -d ".venv" ]; then
            python3 -m venv .venv
          fi

          source .venv/bin/activate
          pip install -r torch-requirements.txt
          pip install -r requirements.txt

          sudo apt-get update
          sudo apt-get install -y ffmpeg libsm6 libxext6

          echo "Restarting the service..."
          sudo systemctl restart yolo.service

          if systemctl is-active --quiet yolo.service; then
            echo "Service restarted successfully."
          else
            echo "Service failed to start."
            exit 1
          fi
